### ISSUE TITLE
study preview

### ISSUE THREAD

**Issue by WorksofFaith** [MORE-Platform/more-studymanager-frontend#278]
no way to preview a study before starting it, implement a preview mode, which can likely work exactly like running the study, but allows fast-forwarding and skipping in time; data can get discarded after preview is stopped and before next preview or proper activation of study occurs (or if braking changes are configured by the study administrator) - Jan

**Comment by alireza-dhp** [comment]
related ticket:https://github.com/MORE-Platform/more-studymanager-backend/issues/224
