### ISSUE TITLE
configuring a trigger - observation property limited

### ISSUE THREAD

**Issue by pavinod** [MORE-Platform/more-studymanager-frontend#310]
for question observations, the operator is limited to equal or not equal to, which is quite limiting eg. for measuring stress on a scale it would need to be greater than or equal to.

Suggestion:include additional operators
(Faith)

**Comment by alireza-dhp** [comment]
In the current simple questionnaire, participants can select only one option from up to five available choices.
That is why the operator is limited to equal or not equal!
