### ISSUE TITLE
Alias name editing for the unused token ( i.e new participants ) should not mandate pausing a  running study 

### ISSUE THREAD

**Issue by devhci** [MORE-Platform/more-studymanager-frontend#357]
Alias name editing for the unused token (i.e., new participants) should not mandate pausing a running study. As participants get recruited on a rolling basis, stopping a study for just changing the alias name for every recruit will annoy the existing study participants. This is because, in the current implementation, on study stop, all participants receive a new study configuration--which leads to same-day observation reaper on study restart (even if they hv already filled them ), + all the previous notification messages disappear on study restart.

**Comment by alireza-dhp** [comment]
Allowing only participants with "new" status (unused tokens) to edit their alias name would be beneficial, as it would prevent confusion between the alias names in the mobile app and the dashboard for active participants.

**Comment by benitsch** [comment]
PR #458 will change the behavior to only allow participants alias change when its status is "new".

**Comment by alireza-dhp** [comment]
Hi @benitsch 

The PR #458 causes a new issue: when the study is paused (or paused preview), it is not possible to edit/update Alias name or study group of active (used tokens) participants!
It should not restrict these edits when the study status is paused.

**Comment by benitsch** [comment]
Thanks for the test, looks like a misunderstanding. PR #461 will now implement the desired behavior.
