### ISSUE TITLE
Issue with scheduling an intervention with multiple conditions on different observations

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-frontend#361]
I have defined three simple questionnaire observations to inquire about the mood (Happy, Sad, Unsure):

![observations](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/d218972d-bb2e-4165-915a-63a12646d9dc)

Mood 9 a.m. (scheduled between 9-10 a.m.)
Mood 1 p.m. (scheduled between 13-14 p.m.)
Mood 7 p.m. (scheduled between 19-20 p.m.)

Additionally, I have set up an intervention to send a message based on the following condition:

![conditions](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/71a30e28-ef5d-40c4-93f2-cfb275851182)

Mode 9 a.m. answer != 'Happy' 
**OR**
Mode 1 p.m. answer != 'Happy' 
**OR**
Mode 7 p.m. answer != 'Happy'

There seems to be an issue in triggering the notification message.
In the above example the notification does not trigger when I answerd the afternoon question. 
However, if I remove the evening observation condition (i.e. Mood 7 p.m. answer != 'Happy'), the trigger works!

**Comment by smeddinck** [comment]
the OR condition fails if any element of the chain contains no data in the checked time-frame

**Comment by smeddinck** [comment]
consider moving to backend

**Comment by benitsch** [comment]
Closed - Moved to Backend: https://github.com/MORE-Platform/more-studymanager-backend/issues/326
