### ISSUE TITLE
Unexpected Behavior in Setting Different Schedulers on Observation Page

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-frontend#363]
### Description:
There is a bug in the functionality of setting a different scheduler on the observation page, with various instances of unexpected behavior:

- ### No Schedule Checkbox Issue:
   - #### Description:
   When attempting to set a different scheduler on the observation page and selecting the "No Schedule" checkbox, various instances of unexpected behavior arise.

   - #### Reproduction Steps:
   1. Navigate to the observation page.
   2. Set a scheduler and save the observation.
   3. Open the scheduler and select the "No Schedule" checkbox.

   - #### Expected Behavior:
   The expectation is that when the "No Schedule" checkbox is ticked, the timeframe set from the beginning of the study should persist until the end of the study.

   - #### Actual Behavior:
   The Scheduler functionality does not work as intended, especially for external observations. The start date and end date time remain unchanged, and sending data via external integration does not function properly.

- ### Daily or Weekly Scheduler Issue:
   - #### Reproduction Steps:
   1. Set the scheduler to daily or weekly.
   2. Observe the displayed observations in the Mobile app.

   - #### Issue:
   The app shows observations for past days.

- ### Weekly Schedule End-of-Study Observation Issue:
   - #### Reproduction Steps:
   1. Define a weekly schedule.
   2. Check the last scheduled observation date on the mobile app.

   - #### Issue:
   The last scheduled observation occurs after the end of the study period.

**Comment by smeddinck** [comment]
need to check whether this persists with latest scheduler updates (enabling both absolute and relative schedules)

**Comment by alireza-dhp** [comment]
Apearntly the issues are solved.
Test on Android, App version: 4.0.15
