### ISSUE TITLE
Improved Data Previews

### ISSUE THREAD

**Issue by smeddinck** [MORE-Platform/more-studymanager-frontend#377]
visualization of recorded data in preselected time-frame

okay to utilize external tools as long as free to integrate & use

**Comment by andresgruber** [comment]
Minimal: Start with a time/period filter in the Study manger!

**Comment by alireza-dhp** [comment]
The potential suggestion for using data visualization frameworks would be:
https://d3js.org
https://www.chartjs.org/

**Comment by ja-fra** [comment]
The current "Monitoring"-Tab shall be extended to a "Monitoring & Data"-Tab:
* Allow drill-down on
    * Observation-Level
    * Group- or Participant-Leven
    * Time-Range
* by default, we show the current textual information about collected datapoints
* each module (observation) can define a "preferred visualization" that suites best the data it collects: chart-type and data-dimensions/fields
* no data-aggregation - we show one line per participant
* fist module to enhance with the new feature: heartrate from polar verity sense
