### ISSUE TITLE
Improved Data Download

### ISSUE THREAD

**Issue by smeddinck** [MORE-Platform/more-studymanager-frontend#378]
allow data download not just for an entire study at a given point in time, but also for: individual participants and/or groups, as well as for preselected time-frames (filtering by date-recorded timestamps for study date) only … also make download resumable and optionally size up in packages for very large datasets .. alternatively provide download links via a shared folders mechanism

has a middleware/service/backend aspect to it as well of course

**Comment by iaigner** [comment]
@smeddinck 
I have a quick question. With the introduction of filters for downloads, would it be more efficient to implement a dedicated 'Downloads' tab that includes all data download options with overarching filter options? Alternatively, we could retain download buttons at the table row levels for participants/groups and incorporate filter options within a download dialog. What approach do you think would better suit our needs?

**Comment by smeddinck** [comment]
Not sure what you think is more straight forward from a user POV. To me right now, the participants and grouping tab does not yet feel overburdened, but a "group-based" download also does not feel most naturally placed there ... it is also not straight forward to integrate with Monitoring, although that seems like a possibility since filtering is already in place there in a similar manner and a "download associated data from the last X days" could easily be added there?

in the longer-term we want to add further interoperability functionalities and these would likely require some room, hence possibly a "Data & Interoperability" tab ... 

In this light, I would propose integrating either with Monitoring, or introducing another tab (although too many tabs would not be helpful) might meaningfully expand the logical flow of what is already there ... if this adds considerable cost / effort compared to integrating with the participants tab, I would also be okay with an integration there as a fallback. 

@devhci @motohit: feel free to expand on this if you have further thoughts

**Comment by iaigner** [comment]
When considering the integration of additional filters, it seems more intuitive for me as well to incorporate them in a manner where overarching settings can be applied to all downloads. Opting for a row-based implementation may introduce a potential inconvenience with dialogs/filters. For instance, if you wish to download only 3 participants out of 50, you may find yourself manually configuring the same filters for each download dialog, resulting in a less efficient user experience.

I believe a more user-friendly and rewarding approach would be to provide the option to configure settings globally for all downloads. This way, users can establish their preferences once, ensuring consistency and ease of use throughout their download interactions.

Regarding the potential integration within the Monitoring tab, its suitability depends on the anticipated growth in download options and data visualization. If the system envisions expanding options for downloads as well as the need for redownloading former created download sets, it might be better to introduce a new tab. Especially when the filter options of the monitoring tab and the download tab might differ in the future. Given the relatively limited number of download options, we could add them to the monitoring tab for the time being, with the option to reevaluate on a later date. Nevertheless, If integrated in the monitoring tab I would tend to use two filter sets for now: one for data, one for download.

**Comment by smeddinck** [comment]
in that case a separate tab sounds like the most reasonable approach to explore straight away to me ...
