### ISSUE TITLE
Participant status after leaving study

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-frontend#436]
The participant's status does not update/change when they leave the study!

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/191

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/192

**Comment by andresgruber** [comment]
The bugfix does not set the "abandoned" status for participants who have left the study in the past. It works for all new studies and running studies, where a participant leaves the study.
