### ISSUE TITLE
Absolute scheduler time picker issues on study start/end dates

### ISSUE THREAD

**Issue by rania-is** [MORE-Platform/more-studymanager-frontend#555]
- When setting the absolute scheduler for the first day of the study, the time picker restricts the start time to 2:00 AM, rather than allowing selection from midnight (00:00).

- For the end date on the last day of the study, the time picker limits selection to 1:00 AM and 00:00.

The issue may stem from how the start and end times are configured for the study period. The time should be set from midnight (00:00) on the first day until 23:59 on the last day,

This is related to issue #541 regarding default scheduler behavior.

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-studymanager-frontend/pull/562

**Comment by andresgruber** [comment]
Default Schedulers now start at 00:00 on the first day and ends at 23:59 on the last day, changing  values is possible!
